---
- name: Check if sysctl.d directory exists
  command: "sysctl -a"
  register: sysctl_all_vars

- name: Set sysctl_file depending on the existance of sysctl.d dir
  set_fact:
    sysctl_file: "/etc/sysctl.conf"
  when: not s.stat.exists

- name: Set sysctl vars and write to file
  command: "sysctl -wq {{ item.key }}={{ item.value|string|quote }}"
  ignore_errors: "{{ sysctl_ignore_errors|default(true) }}"
  with_dict: "{{ sysctl }}"
  when: "'{{ item.key }} = {{ item.value }}' not in sysctl_all_vars.stdout"

- name: Set sysctl vars in autoload file
  template:
    src: "sysctl.conf.j2"
    dest: "{{ sysctl_file }}"
    owner: root
    group: root
    mode: 0644
