---
- name: Check if sysctl.d directory exists
  stat:
    path: "/etc/sysctl.d/{{ sysctl_file }}"
  register: s

- name: Set sysctl_file depending on the existance of sysctl.d dir
  set_fact:
    sysctl_file: "/etc/sysctl.conf"
  when: not s.stat.exists

- name: Create empty sysctl conf file template
  copy:
    content: ""
    dest: "{{ sysctl_file }}"
    owner: root
    group: root
    mode: 0644
  when: not s.stat.exists

- name: Set sysctl vars and write to file
  command: "sysctl -wq {{ item.key }}={{ item.value|quote }}"
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: "{{ item.value.state|default('present') }}"
    ignoreerrors: "{{ item.value.ignoreerrors|default('yes') }}"
    reload: no
    sysctl_set: yes
  with_dict: "{{ sysctl }}"
  when: "{{ item.key }} = {{ item.value }}" not in sysctl_all_vars.stdout

- name: Set sysctl vars in autoload file
  template:
    src: "sysctl.conf.j2"
    dest: "{{ sysctl_file }}"
    owner: root
    group: root
    mode: 0644
